### ISSUE TITLE
how should i refine the parameter on Inclined plane

### ISSUE THREAD

**Issue by jiqirenno1** [horizon-research/Real-Time-Spatio-Temporal-LiDAR-Point-Cloud-Compression#3]
i try the code on my own data, but i can not recover the pointcloud ,how should i refine the parameter.
my device is robosen-lidar-16, it scans a river bank.
my encoder code as below (the white points are the original points, the green points are get after encode and decode ):
```
./pcc_encoder --path ./data --file ori.bin -p 0.18 -y 2 -f binary -l 4 -t 1 --out 1.tar.gz

```
![Screenshot from 2021-03-03 16-54-23](https://user-images.githubusercontent.com/30222420/109786154-d6036100-7c47-11eb-88db-f9265a53e7a7.png)

**Comment by YuFengUofR** [comment]
There are several possibilities:
1. you can look into "config.h" file, and tweak the FOV of the range map: https://github.com/horizon-research/Real-Time-Spatio-Temporal-LiDAR-Point-Cloud-Compression/blob/master/src/config.h
2.  what is the range of your data? I assume the maximum data range is ~100m. This could lead to some problems.

**Comment by jiqirenno1** [comment]
Thank you for your reply. I'll try again
