### ISSUE TITLE
IMU usage

### ISSUE THREAD

**Issue by creniq** [horizon-research/Real-Time-Spatio-Temporal-LiDAR-Point-Cloud-Compression#4]
Dear developers:

In your paper, it was mentioned that IMU is used to transform P-frame to K- frame’s coordinate system. However I'm not seeing any mention of IMU in the code. Is this omission intended? Are the frames in your stream encoding/decoding sample already transformed? Without the use of IMU, would the code still work (but perhaps with decreased compression rate)?

Thank you in advance for your reply!

**Comment by YuFengUofR** [comment]
Yes, in the code itself, I didn't include the transformation information, but you can transform the point cloud ahead of time. If you aggregate with a small set of frames (< 10 frames), directly aggregating the point cloud without transformation still works.

**Comment by creniq** [comment]
@YuFengUofR Thank you very much for your reply. Do you plan to share a more complete implementation? In addition to IMU, the parallelization of computation is also missing from the code. I really like the ideas, and would like to use them in our product. But with the code that's currently shared, it would take a lot of effort to adapt it to a real world setting.

**Comment by YuFengUofR** [comment]
currently, I am not planning to work on this project. You can use OpenMP and add some pragmas in the encoder and decoder code, it will easily improve the performance by several times speedup.

**Comment by creniq** [comment]
Thanks for the info.
