### ISSUE TITLE
Issue on the implemention of the plane fitting 

### ISSUE THREAD

**Issue by ZorAttC** [horizon-research/Real-Time-Spatio-Temporal-LiDAR-Point-Cloud-Compression#5]
I think there's a problem with the implemention of plane fitting,e.g.
the plane fitting equation is a*r+b*i+c*j+d=0,where the normal vector consists of  (a,b,c) ,r is the range,i and j is the pixel coordinates. If r is fixed but i,j is loose, definitely it is a plane of (r,i,j).But in the xyz coordinates,it is a part of a sphere's surface,and it will distort the result.

![2024-04-02 13-38-18 的屏幕截图](https://github.com/horizon-research/Real-Time-Spatio-Temporal-LiDAR-Point-Cloud-Compression/assets/93999826/df0d6b38-7147-4a74-bea9-a2bcbd046647)

As you can see,the wall tends to be bent.

**Comment by tfoldi** [comment]
how did you fix this?

**Comment by ZorAttC** [comment]
This is not a bug, it's feature :(



---Original---
From: "Földi ***@***.***&gt;
Date: Tue, Sep 24, 2024 15:13 PM
To: ***@***.***&gt;;
Cc: "Yuhao ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re:[horizon-research/Real-Time-Spatio-Temporal-LiDAR-Point-Cloud-Compression]Issue on the implemention of the plane fitting  (Issue #5)




 
how did you fix this?

**Comment by chunibyo-wly** [comment]
True, this equation appears to be an approximation of the surface of a sphere.
As delta approaches zero, the curve(surface) becomes a straight line(plane).

Since the relationship between $r$ and `pixel coordinates` is not linear (trigonometric) compared to Cartesian coordinates.
So, would it be possible to fit the plane using the original Cartesian coordinates(without considering efficiency) to achieve more precise results?

**Comment by ZorAttC** [comment]
> True, this equation appears to be an approximation of the surface of a sphere. As delta approaches zero, the curve(surface) becomes a straight line(plane).
> 
> Since the relationship between r and `pixel coordinates` is not linear (trigonometric) compared to Cartesian coordinates. So, would it be possible to fit the plane using the original Cartesian coordinates(without considering efficiency) to achieve more precise results?

Actually in my experiment,because of the numerical accuracy of the Cartesian plane parameters,it will get lower performance than this kind of implemention.
